In [1]:
import pandas as pd
import os

print(os.getcwd())
clustered = pd.read_csv("outputs/clustered_students.csv")
clustered.head()

d:\minor project code

,dataplus,dualpane,externalquiz,folder,forumng,glossary,homepage,oucollaborate,oucontent,ouelluminate,ouwiki,page,questionnaire,quiz,resource,sharedsubpage,subpage,url,cluster,cluster_label
0,0,0,0,0,255,3,393,13,905,0,0,0,14,501,89,0,135,6,2,High Engagement
1,0,0,0,0,16,1,63,19,53,0,0,0,0,5,30,0,15,1,0,Moderate Engagement
2,0,0,0,0,135,0,98,8,114,0,0,0,0,55,10,0,7,0,0,Moderate Engagement
3,0,0,0,0,0,0,96,0,151,0,0,0,0,152,21,0,16,2,0,Moderate Engagement
4,0,0,0,0,104,0,54,0,0,0,0,0,0,16,1,0,8,9,0,Moderate Engagement

In [22]:
clustered.head()
clustered.columns

Index(['dataplus', 'dualpane', 'externalquiz', 'folder', 'forumng', 'glossary',
       'homepage', 'oucollaborate', 'oucontent', 'ouelluminate', 'ouwiki',
       'page', 'questionnaire', 'quiz', 'resource', 'sharedsubpage', 'subpage',
       'url', 'cluster', 'cluster_label'],
      dtype='str')

In [23]:
pd.read_csv("outputs/clustered_students.csv").head()

,id_student,dataplus,dualpane,externalquiz,folder,forumng,glossary,homepage,oucollaborate,oucontent,...,ouwiki,page,questionnaire,quiz,resource,sharedsubpage,subpage,url,cluster,cluster_label
0,26734,0,0,0,0,16,1,63,19,53,...,0,0,0,5,30,0,15,1,0,Moderate Engagement
1,32327,0,0,0,0,135,0,98,8,114,...,0,0,0,55,10,0,7,0,0,Moderate Engagement
2,32930,0,0,0,0,0,0,96,0,151,...,0,0,0,152,21,0,16,2,0,Moderate Engagement
3,34431,0,0,0,0,104,0,54,0,0,...,0,0,0,16,1,0,8,9,0,Moderate Engagement
4,34662,0,0,0,0,14,0,106,2,62,...,0,0,0,0,20,0,8,2,0,Moderate Engagement

In [3]:
# identifying columns with zero values and further dropping them 

# Separate feature columns explicitly
feature_cols = clustered.drop(columns=["cluster", "cluster_label"], errors="ignore")

# Identify columns that are zero for all students
zero_cols = feature_cols.columns[(feature_cols == 0).all()]

zero_cols

Index(['dataplus', 'dualpane', 'externalquiz', 'folder'], dtype='str')

In [4]:
clustered_clean = clustered.drop(columns=zero_cols)

clustered_clean.head()

,forumng,glossary,homepage,oucollaborate,oucontent,ouelluminate,ouwiki,page,questionnaire,quiz,resource,sharedsubpage,subpage,url,cluster,cluster_label
0,255,3,393,13,905,0,0,0,14,501,89,0,135,6,2,High Engagement
1,16,1,63,19,53,0,0,0,0,5,30,0,15,1,0,Moderate Engagement
2,135,0,98,8,114,0,0,0,0,55,10,0,7,0,0,Moderate Engagement
3,0,0,96,0,151,0,0,0,0,152,21,0,16,2,0,Moderate Engagement
4,104,0,54,0,0,0,0,0,0,16,1,0,8,9,0,Moderate Engagement

In [8]:
numeric_features = clustered_clean.select_dtypes(include="number")

numeric_features = numeric_features.drop(columns=["cluster"], errors="ignore")

usage_counts = (numeric_features > 0).sum()
usage_counts.sort_values()

ouwiki              1
page                1
sharedsubpage       1
ouelluminate        4
questionnaire     702
glossary          833
oucollaborate    1090
url              1205
forumng          1390
quiz             1417
subpage          1802
oucontent        1825
resource         1838
homepage         1863
dtype: int64

In [9]:
threshold = 0.01 * len(numeric_features)

low_usage_cols = usage_counts[usage_counts < threshold].index

low_usage_cols

Index(['ouelluminate', 'ouwiki', 'page', 'sharedsubpage'], dtype='str')

In [10]:
clustered_final = clustered_clean.drop(columns=low_usage_cols)

clustered_final.head()

,forumng,glossary,homepage,oucollaborate,oucontent,questionnaire,quiz,resource,subpage,url,cluster,cluster_label
0,255,3,393,13,905,14,501,89,135,6,2,High Engagement
1,16,1,63,19,53,0,5,30,15,1,0,Moderate Engagement
2,135,0,98,8,114,0,55,10,7,0,0,Moderate Engagement
3,0,0,96,0,151,0,152,21,16,2,0,Moderate Engagement
4,104,0,54,0,0,0,16,1,8,9,0,Moderate Engagement

In [24]:
clustered_final.columns

Index(['forumng', 'glossary', 'homepage', 'oucollaborate', 'oucontent',
       'questionnaire', 'quiz', 'resource', 'subpage', 'url', 'cluster',
       'cluster_label'],
      dtype='str')

In [25]:
student_info = pd.read_csv("data/studentInfo.csv")

labels = student_info[["id_student", "final_result"]].copy()

labels["target"] = labels["final_result"].apply(
    lambda x: 0 if x in ["Pass", "Distinction"] else 1
)

labels["target"].value_counts()

target
1    17208
0    15385
Name: count, dtype: int64

In [27]:
print("clustered columns:", clustered.columns)
print("csv columns:", pd.read_csv("outputs/clustered_students.csv").columns)

clustered columns: Index(['dataplus', 'dualpane', 'externalquiz', 'folder', 'forumng', 'glossary',
       'homepage', 'oucollaborate', 'oucontent', 'ouelluminate', 'ouwiki',
       'page', 'questionnaire', 'quiz', 'resource', 'sharedsubpage', 'subpage',
       'url', 'cluster', 'cluster_label'],
      dtype='str')
csv columns: Index(['id_student', 'dataplus', 'dualpane', 'externalquiz', 'folder',
       'forumng', 'glossary', 'homepage', 'oucollaborate', 'oucontent',
       'ouelluminate', 'ouwiki', 'page', 'questionnaire', 'quiz', 'resource',
       'sharedsubpage', 'subpage', 'url', 'cluster', 'cluster_label'],
      dtype='str')

In [28]:
clustered = pd.read_csv("outputs/clustered_students.csv")

In [29]:
clustered.columns

Index(['id_student', 'dataplus', 'dualpane', 'externalquiz', 'folder',
       'forumng', 'glossary', 'homepage', 'oucollaborate', 'oucontent',
       'ouelluminate', 'ouwiki', 'page', 'questionnaire', 'quiz', 'resource',
       'sharedsubpage', 'subpage', 'url', 'cluster', 'cluster_label'],
      dtype='str')

In [30]:
final_dataset = clustered.merge(
    labels[["id_student", "target"]],
    on="id_student",
    how="inner"
)

final_dataset.shape

(943, 22)

In [ ]:

final_dataset["target"].value_counts()

target
1    631
0    312
Name: count, dtype: int64

In [34]:
final_dataset.shape

(943, 22)

In [35]:
behavior_cols = [
    col for col in final_dataset.columns
    if col not in ["id_student", "cluster", "cluster_label", "target"]
]

final_dataset_active = final_dataset[
    final_dataset[behavior_cols].sum(axis=1) > 0
]

final_dataset_active.shape
final_dataset_active["target"].value_counts()

target
1    631
0    312
Name: count, dtype: int64

In [36]:
final_dataset_active.to_csv(
    "outputs/final_prediction_dataset.csv",
    index=False
)